DROP DATABASE web_homework;
CREATE DATABASE IF NOT EXISTS web_homework CHARACTER SET UTF8;
USE web_homework;

CREATE TABLE IF NOT EXISTS USER(
 user_id BIGINT(18) NOT NULL AUTO_INCREMENT,
 nickname VARCHAR(20) NOT NULL DEFAULT '',
 PASSWORD VARCHAR(20) NOT NULL DEFAULT '',
 school VARCHAR(20) DEFAULT NULL,
 major VARCHAR(10) DEFAULT NULL,
 grade VARCHAR(5) DEFAULT NULL,
 sex VARCHAR(5) DEFAULT NULL,
 age INT DEFAULT NULL,
 img_path VARCHAR(20) DEFAULT NULL,
 PRIMARY KEY(user_id)
);

CREATE TABLE IF NOT EXISTS tag(
tag_id INT(10) NOT NULL AUTO_INCREMENT,
tag_name VARCHAR(10),
tag_type VARCHAR(10),
PRIMARY KEY(tag_id)
);

CREATE TABLE IF NOT EXISTS question(
 q_id BIGINT(18) NOT NULL AUTO_INCREMENT,
 q_title VARCHAR(20),
 q_content TEXT,
 q_like_num BIGINT,
 q_collect_num BIGINT,
 createTime DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
 updateTime DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
 user_id BIGINT(18),
 PRIMARY KEY(q_id),
 FOREIGN KEY (user_id) REFERENCES USER(user_id)
);
CREATE TABLE IF NOT EXISTS tag_question(
table_id BIGINT(18) NOT NULL AUTO_INCREMENT,
q_id BIGINT(18),
tag_id INT(10),
PRIMARY KEY(table_id),
FOREIGN KEY (q_id) REFERENCES question(q_id),
FOREIGN KEY (tag_id) REFERENCES tag(tag_id)
);
ALTER TABLE USER ADD user_coin INT(8) DEFAULT 10;
ALTER TABLE USER ALTER img_path SET DEFAULT "默认头像.png";`resource`