USE web_homework;

CREATE TABLE IF NOT EXISTS note(
 note_id BIGINT(18) NOT NULL AUTO_INCREMENT,
 note_title VARCHAR(30)NOT NULL,
 note_intro VARCHAR(30)NOT NULL,
 note_content TEXT NOT NULL,
 createtime DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
 user_id BIGINT(18)NOT NULL,
 PRIMARY KEY(note_id),
 FOREIGN KEY(user_id) REFERENCES USER(user_id)
);

CREATE TABLE IF NOT EXISTS like_n(
 like_id BIGINT(18) NOT NULL AUTO_INCREMENT,
 note_id BIGINT(18) NOT NULL ,
 user_id BIGINT(18)NOT NULL,
 createTime DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
 PRIMARY KEY(like_id),
 FOREIGN KEY(note_id) REFERENCES note(note_id),
 FOREIGN KEY(user_id) REFERENCES USER(user_id)
);

CREATE TABLE IF NOT EXISTS collect_n(
 collect_id BIGINT(18) NOT NULL AUTO_INCREMENT,
 note_id BIGINT(18) NOT NULL ,
 user_id BIGINT(18)NOT NULL,
 createTime DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
 PRIMARY KEY(collect_id),
 FOREIGN KEY(note_id) REFERENCES note(note_id),
 FOREIGN KEY(user_id) REFERENCES USER(user_id)
);
DROP TABLE answer;
CREATE TABLE IF NOT EXISTS answer(
 answer_id BIGINT(18) NOT NULL AUTO_INCREMENT,
 content TEXT NOT NULL,
 createtime DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
 q_id BIGINT(18) NOT NULL ,
 user_id BIGINT(18)NOT NULL,
 PRIMARY KEY(answer_id),
 FOREIGN KEY(q_id) REFERENCES question(q_id),
 FOREIGN KEY(user_id) REFERENCES USER(user_id)
);



